name: CI Pipeline

on:
  push:
    branches:
    -  main
  # pull_request:
  #   branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry using PAT
      run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        IMAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/$IMAGE_NAME:1.0 .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}:1.0
    
    # - name: Set up environment
    #   run: echo "Setting up build environment"
    
    # - name: Build
    #   run: docker build -t dev_app .
    
    # - name: Test
    #   run: echo "Running tests"
    
    # - name: Deploy
    #   run: echo "Deploying application"